[package]
name = "rs256"
version = "0.1.0"
authors = ["Kiëd Llaentenn <32681240+kiedtl@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
